### ISSUE TITLE
Transform stage create o byte files

### ISSUE THREAD

**Issue by praveen-kg** [eriknelson/hello-crane-demo#1]
Hi, I  exploring the crane tool and with your great post, I tried to explore Crane tool. I am able to export from OPC 3.11 cluster a name space and when I try to change the namespace name using transform command in CLI,  it generates 0 byte transformed files. Logs  as below
time="2021-10-07T14:41:51+05:30" level=info msg="resource file: Deployment_test0508-dev_amqstreams-my-cluster-entity-operator.yaml creating whiteout file: D:\\GoWorkspace\\crane-main\\transform\\.wh.Deployment_test0508-dev_amqstreams-my-cluster-entity-operator.yaml"
time="2021-10-07T14:41:51+05:30" level=info msg="resource file: ReplicaSet_test0508-dev_amqstreams-strimzi-cluster-operator-76f66979c7.yaml creating whiteout file: D:\\GoWorkspace\\crane-main\\transform\\.wh.ReplicaSet_test0508-dev_amqstreams-strimzi-cluster-operator-76f66979c7.yaml"

Not seeing any exception though I have enabled debug with this command, not seen much log.

Please let me know  what should be done here to do a transformation to update namespace and remove status tag.

**Comment by praveen-kg** [comment]
closing, as with some environment changes, it works.

**Comment by eriknelson** [comment]
Hi @praveen-kg, glad to hear you got it sorted out. The readme here is potentially out of date as the tooling itself is *rapidly* being developed right now. It's great you're trying things out early, we'd love your feedback and can help you work through any issues you're seeing. Please join #konveyor in the kubernetes slack instance, as this is where our engineers can be found for real time discussion

**Comment by praveen-kg** [comment]
@eriknelson : Thanks for the reply. I have another challenge and while I am doing the transformation and provided the plugins directory along with transform command, it is not picking and not applying the namespace change. Could you pls let me know what's wrong I am doing ?
